# CAUTION: THIS FILE IS FOR DEMONSTRATION PURPOSES ONLY
# DO NOT UPLOAD SECRETS TO YOUR GIT REPOSITORY !!!!
# Secrets must be encoded using base64 (ensure there is no newline at the end of the file):
# echo -n 'mysupersecretpassword' | base64 -w0

apiVersion: v1
kind: Secret
metadata:
  name: tactical-secrets
  namespace: tacticalrmm
data:
  # Default password: changeme
  trmm-password: Y2hhbmdlbWU=
  mesh-password: Y2hhbmdlbWU=
  mongodb-password: Y2hhbmdlbWU=
  postgres-password: Y2hhbmdlbWU=
